#pragma once

/**
 * @file plugin_manager.hpp
 * @brief Runtime loader and registry for language plugins.
 *
 * LangPluginManager replaces the old compile-time `lang_factory.hpp`
 * (generated by languages/scripts/generate_lang_factory.py). Instead of
 * baking the extension → class dispatch into the binary at configure time,
 * the manager discovers plugins at runtime: it loads each `.so`/`.dll`,
 * queries its LangPlugin descriptor, and builds an extension → plugin table.
 *
 * It preserves the public surface the rest of the codebase already expects:
 *   - is_supported(path)
 *   - make_lang_analyze(path)  ->  std::shared_ptr<LangAnalyze>
 *
 * ## Routing: regex patterns, ordered by priority
 *
 * Dispatch is no longer an extension → plugin hash table. Each plugin exposes a
 * single regex (LangPlugin::file_pattern()) matched against a file's *name*, so
 * fixed-name/extensionless files (Dockerfile, CMakeLists.txt) route correctly.
 * At load time plugins are ordered by LangPlugin::priority() (highest first,
 * load order breaking ties); routing walks that fixed order and picks the first
 * plugin whose pattern matches. A low-priority catch-all is thus overridden by
 * any dedicated plugin without touching the catch-all's pattern. The plugin
 * count is small, so linear scan per file is negligible.
 *
 * ## Lifetime safety (the crux of plugin mode)
 *
 * A LangAnalyze produced by a plugin has its code and vtable inside the
 * plugin's dynamic library. If the library unloads while an analyzer is still
 * alive, any call (including ~LangAnalyze) is undefined behavior. A bare
 * shared_ptr<LangAnalyze> does NOT keep the library loaded.
 *
 * The manager solves this by keeping, per plugin, a shared_ptr to its
 * boost::dll::shared_library, and by binding that shared_ptr into the
 * *deleter* of every analyzer shared_ptr it returns. Destruction order is then
 * guaranteed: the analyzer is destroyed first (its dtor code is still mapped),
 * then the captured library reference drops. The library only truly unloads
 * once the manager and every analyzer it ever produced are gone. This keeps
 * the original shared_ptr-based RAII design working unchanged for callers.
 *
 * ## Singleton
 *
 * There is exactly one manager per process, reached through instance(). Since
 * the query surface is const and safe under concurrent readers, the only
 * mutation — loading plugins — is funnelled through ensure_loaded(), which uses
 * std::call_once so plugins are discovered exactly once no matter how many
 * threads race to trigger it. The pattern is: call ensure_loaded() during
 * startup (or let the first query-site trigger it), after which the manager is
 * effectively immutable and every query method is safe to call concurrently.
 */

#include <filesystem>
#include <memory>
#include <mutex>
#include <regex>
#include <string>
#include <vector>

#include <boost/dll/shared_library.hpp>
#include <boost/dll/import.hpp>

#include "lang.hpp"
#include "lang_plugin.hpp"

namespace indextools {

/**
 * @brief Process-wide loader that routes files to the right analyzer.
 *
 * Access the sole instance via instance(). Trigger discovery once with
 * ensure_loaded() (idempotent, thread-safe via std::call_once); afterwards the
 * manager is read-only and its const query methods are safe to call
 * concurrently.
 */
class LangPluginManager {
public:
    using AnalyzePtr = std::shared_ptr<LangAnalyze>;

    /**
     * @brief The one manager for this process.
     *
     * Constructed on first call (thread-safe static-local init). Destroyed at
     * process exit; analyzers already handed out stay valid because each holds
     * its own library reference through its deleter (see file header).
     */
    static LangPluginManager& instance();

    /**
     * @brief Load plugins exactly once, from `<executable_dir>/plugins`.
     *
     * The first caller performs discovery; concurrent and subsequent callers
     * block until it finishes, then return without reloading. Safe to call from
     * any thread and as many times as you like.
     *
     * @return The number of plugins loaded by the one-time discovery.
     */
    size_t ensure_loaded();

    /**
     * @brief Load plugins exactly once, from an explicit @p directory.
     *
     * Same one-shot semantics as ensure_loaded(); the directory of the first
     * winning call is the one used. Intended for tests and non-default layouts.
     */
    size_t ensure_loaded(const std::filesystem::path& directory);

private:
    /// One loaded plugin: the library (kept alive), its descriptor, and its
    /// compiled file-name matcher.
    struct LoadedPlugin {
        // Declaration order matters: `plugin` (living inside `library`) must be
        // destroyed before `library`. Members destruct in reverse declaration
        // order, so `library` is declared first and destroyed last.
        std::shared_ptr<boost::dll::shared_library> library;
        std::shared_ptr<LangPlugin> plugin;
        // Compiled once from plugin->file_pattern() at load time (host-side, so
        // it does not outlive `library` illegitimately). Case-insensitive.
        std::regex pattern;
    };

    /// All successfully loaded plugins. Populated in load order, then reordered
    /// once (highest priority() first, load order breaking ties) at the end of
    /// discovery so routing can take the first matching entry. See
    /// _finalize_order().
    std::vector<LoadedPlugin> _plugins;

    /// Guards the one-time discovery driven by ensure_loaded().
    std::once_flag _load_once;

    // A singleton: constructed only by instance(), never copied or moved.
    LangPluginManager() = default;
    ~LangPluginManager() = default;
    LangPluginManager(const LangPluginManager&) = delete;
    LangPluginManager& operator=(const LangPluginManager&) = delete;
    LangPluginManager(LangPluginManager&&) = delete;
    LangPluginManager& operator=(LangPluginManager&&) = delete;

    /**
     * @brief Load a single plugin library from an explicit path.
     *
     * Loads the library, imports the LANG_PLUGIN_FACTORY_NAME alias, builds the
     * plugin descriptor, verifies its ABI version, and compiles its
     * file_pattern() regex. On any failure (including an invalid pattern) the
     * library is discarded and false is returned; already-loaded plugins are
     * unaffected. Note this appends in load order; call _finalize_order() once
     * after a batch to establish the priority-based routing order.
     *
     * @param library_path Path to the plugin. `append_decorations` is applied,
     *        so a bare stem ("langpy") or a full "liblangpy.so" both work.
     * @return true if the plugin loaded and registered at least its metadata.
     */
    bool load(const std::filesystem::path& library_path);

    /**
     * @brief Load every plugin found directly inside @p directory.
     *
     * Scans for regular files with a platform dynamic-library extension and
     * calls load() on each. Files that fail to load are logged to std::cerr
     * and skipped — one bad plugin does not abort discovery.
     *
     * @return The number of plugins successfully loaded.
     */
    size_t load_directory(const std::filesystem::path& directory);

    /**
     * @brief Convenience: load plugins from `<executable_dir>/plugins`.
     *
     * Uses boost::dll::program_location() so it works regardless of the
     * current working directory. This is the default the host uses at startup.
     *
     * @return The number of plugins successfully loaded.
     */
    size_t load_default_directory();

    /**
     * @brief Freeze the routing order after a batch of load()s.
     *
     * Stable-sorts _plugins by priority() descending. The stable sort keeps
     * load order among equal priorities, so routing is deterministic and a
     * dedicated plugin always precedes a lower-priority catch-all. Called once
     * per discovery, from load_directory().
     */
    void _finalize_order();

public:
    // ------------------------------------------------------------------ query

    /// Number of loaded plugins.
    size_t plugin_count() const noexcept { return _plugins.size(); }

    /**
     * @brief Whether some loaded plugin's pattern matches @p file_path's name.
     *
     * Case-insensitive regex match against the file name (not the full path).
     * Unlike the old generated helper, this does NOT check file existence —
     * routing is a pure name decision; existence is the caller's concern (see
     * CacheSystem, which canonicalizes).
     */
    bool is_supported(const std::filesystem::path& file_path) const noexcept;

    /**
     * @brief Create an analyzer for @p file_path, or nullptr if unsupported.
     *
     * The returned shared_ptr owns the analyzer and, via its deleter, a
     * reference to the plugin's library — guaranteeing the library outlives
     * the analyzer. The caller then drives open()/load()/analyze() as before.
     */
    AnalyzePtr make_lang_analyze(const std::filesystem::path& file_path) const;

private:
    /// Index of the first plugin (in routing order) whose pattern matches
    /// @p file_path's name, or npos if none does.
    size_t _match_plugin(const std::filesystem::path& file_path) const noexcept;

    /// True if @p path has a platform dynamic-library extension.
    static bool _is_dynamic_library(const std::filesystem::path& path) noexcept;
};

}
